version: "3.8"

networks:
  arango:
   external: false

services:
  arangodb:
    image: arangodb/arangodb
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=3e8M@uy§'PFZ2PU_
    networks:
      - arango
    volumes:
     - arangodb:/var/lib/arangodb3

volumes:
  arangodb:
